# Generated by Django 6.0 on 2025-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodO', '0002_restaurantuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
