# Generated by Django 6.0 on 2025-12-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodO', '0004_dashboardstats_pickuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='ngo_name',
            field=models.CharField(default='NGO', max_length=100),
        ),
    ]
